### ISSUE TITLE
Removal of 'Dedicated' entries?

### ISSUE THREAD

**Issue by jabberjabberjabber** [roydejong/bssb.app#15]
I am curious if the removal of the 'Dedicated' list with the brief history has been removed permanently. It was useful to be able to go back and check a recent game and see who the other players were and which maps were played. If there is a problem with keeping it or maintaining it I understand, but If you assumed no one cared about it I can say at least one person did. 

I appreciate the hard work you put in and am constantly amazed at the quality of this service.

**Comment by roydejong** [comment]
Thanks for reaching out, I'll keep this in mind and see if I can find a way to bring it back.

This app runs on a pretty small server and the dedicated server list was running a very heavy query - to the extent that it caused the entire app to go down at times. I absolutely assumed no one actually used this list, so removed rather than optimized.

**Comment by jabberjabberjabber** [comment]
Not a big deal. Just wondering if I would need to find another way to find players I had gamed with to add to steam friends. All I have to do is find the info in my server log (since that's the only one I use). Guess I found a new project to work on!
